// <auto-generated />
namespace ASPNetOgameLikeTP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Partie71 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Partie71));
        
        string IMigrationMetadata.Id
        {
            get { return "202007211015308_Partie7-1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
